#!/bin/bash

set -eu

usage () {
    echo "$0"
    echo "  Try to apply the last failed patch via wiggle, updating"
    echo "  the patch if successful."
    exit 1
}

if [ $# -ne 0 ]; then
    usage
fi

file=$(readlink "$CJ_GIT_PATCHTOOL_BASEDIR"/_applying)

cj-git-patchtool-wiggle "$file"

